# apiVersion:
# kind: 
# metadata:
# spec:

# Single Pod Single Container Example

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:stable
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
  - name: httpd-container
    image: httpd
    ports:
    - containerPort: 81