# Creating Secrets

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  password: cGFzc3dvcmQK   # Its in base64 format
  API_Token: cXdhc3p4ZXdkc2N4cmVmZHZjCg==  # Its in base64 format



---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret
    image: httpd
    envFrom:
      - configMapRef:
        name: mysecret

