# Creating Secrets

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  password: password
  API_Token: qwaszxewdscxrefdvc



---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret
    image: httpd
    envFrom:
    - configMapRef:
      name: mysecret

