# Purpose of Readiness Probes:
#   Traffic Control: Readiness probes help control which Pods are used as backends for Services.
#   Pod Readiness: A Pod is considered ready when all of its containers are ready. If a container is not ready, the Pod is removed from Service load balancers.
# How It Works:
#   When a Pod starts, the kubelet uses readiness probes to determine if a container is ready to accept traffic.
#   If the readiness probe fails, the kubelet marks the Pod as not ready, preventing it from receiving traffic.
#   This ensures that only fully operational containers participate in serving requests.

# Example of Readiness Probe

apiVersion: v1
kind: Pod
metadata:
  name: goproxy
  labels:
    app: goproxy
spec:
  containers:
  - name: goproxy
    image: registry.k8s.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
