apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-rs
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 10
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 20
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80  
        
--- 
# Creating ClusterIP Service ( this is the default type ) 
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# In deployment, there are 2 types of strategies :
# 1) Rolling Update 
# 2) Recreate 